# Feature Engineering

 The obejective of this notebook is to create meaningful features from the cleaned telecom customer churn dataset. These engineered features help capture customer behaviour more effectively and improve prediction in machine learning models.

In [72]:
# import libraries

import pandas as pd
import numpy as np

In [73]:
# load processed dataset

df = pd.read_csv("../data/processed/cleaned_telco_churn.csv")

In [74]:
# dataset informtion
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

### Observation

The processed dataset contains cleaned customer records with no missing values or duplicate entries. This dataset is now ready for feature engineering.

In [75]:
# create TotalServices Feature

service_columns=[
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "DeviceProtection",
    "TechSupport",
    "OnlineBackup",
    "DeviceProtection",
    "StreamingTV",
    "StreamingMovies"
]

df["TotalServices"]=(
    df[service_columns]
    .replace({
        "Yes":1,
        "No":0,
        "No internet service":0,
        "No phone service":0,
        "DSL":1,
        "Fiber optic":1
    })
    .sum(axis=1)
)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_7604\1382146276.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

In [76]:
df['TotalServices'].head()

0    2
1    5
2    4
3    5
4    2
Name: TotalServices, dtype: int64

### Observation

The TotalSevices feature represents the total number of telecom services subscribed to by each customer. This feature may help identify whether customers with more subscribed services are less likely to churn.

In [77]:
# create Tenure Feature

df['TenureGroup'] = pd.cut(
    df['tenure'],
    bins=[0,12,24,48,72],
    labels=['0-12','13-24','25-48','49-72']
)

In [78]:
df["TenureGroup"].value_counts()

TenureGroup
49-72    2239
0-12     2175
25-48    1594
13-24    1024
Name: count, dtype: int64

### Observation

Customer tenure was grouped into meaningful ranges representing different ages of the customer lifecycle. This may help the model identify churn patterns across new and long term customers.

In [79]:
# create MonethlyChargeCategory Feature

df["MonthlyChargeCategory"] =pd.cut(
    df['MonthlyCharges'],
    bins=[0,35,70,120],
    labels=['Low','Medium','High']
)

In [80]:
df['MonthlyChargeCategory'].value_counts()

MonthlyChargeCategory
High      3581
Low       1729
Medium    1722
Name: count, dtype: int64

In [81]:
df[["MonthlyCharges","MonthlyChargeCategory"]].head()

   MonthlyCharges MonthlyChargeCategory
0           29.85                   Low
1           56.95                Medium
2           53.85                Medium
3           42.30                Medium
4           70.70                  High

### Observation

Monthly charges were categorised into spending groups. Grouping contionous values into categories can simplify customer segementation and improve model interpretability.

In [82]:
# create LongTermCustomer Feature
#np.where(condition, value_if_true, value_if_false)

df['LongTermCustomer']= np.where(df["tenure"]>= 24,1,0)

In [83]:
df['LongTermCustomer'].value_counts()

LongTermCustomer
1    3927
0    3105
Name: count, dtype: int64

### Observation

Customers with a tenure of 24 months or more were labelled as long-term customers. This faeture helps to distinguish loyal customers from new customers.

In [84]:
# preview of the dataset

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TotalServices,TenureGroup,MonthlyChargeCategory,LongTermCustomer
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,2,0-12,Low,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,One year,No,Mailed check,56.95,1889.50,No,5,25-48,Medium,1
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,4,0-12,Medium,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,5,25-48,Medium,1
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,2,0-12,High,0

### Observtion

The dataset now contains additional engineered features derived from existing customer information. These features provide richer information for machine learning models.

In [ ]:
# save feature engineered dataset

df.to_csv("../data/processed/feature_engineered_telco_churn.csv", index=False)

# Summary

### Key Findings

Four new features were successfully created:

- TotalServices
- TenureGroup
- MonthlyChargeCategory
- LongTermCustomer

These features capture customer behavior, service usage, spending patterns, and loyalty. The updated dataset has been saved and is now ready for categorical encoding and machine learning model training.