# Model Training

## Objective

The objective of thi notebook is to prepare the encoded dataset for machine learning for machine learning by seperating the features and target variable,followed by splitting the data into training and testing case.

In [42]:
# Import libraries

import pandas as pd
from sklearn.model_selection  import train_test_split

In [43]:
# Load dataset

df= pd.read_csv("../data/processed/encoded_telco_churn.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,TenureGroup_0-12,TenureGroup_13-24,TenureGroup_25-48,TenureGroup_49-72,MonthlyChargeCategory_High,MonthlyChargeCategory_Low,MonthlyChargeCategory_Medium
0,0,0,1,0,1,0,1,29.85,29.85,0,...,0,1,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,0,0,1,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,1,...,0,0,1,1,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,2,1,1,70.70,151.65,1,...,0,1,0,1,0,0,0,1,0,0

In [44]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 50 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   gender                                   7032 non-null   int64
 1   SeniorCitizen                            7032 non-null   int64
 2   Partner                                  7032 non-null   int64
 3   Dependents                               7032 non-null   int64
 4   tenure                                   7032 non-null   int64
 5   PhoneService                             7032 non-null   int64
 6   PaperlessBilling                         7032 non-null   int64
 7   MonthlyCharges                           7032 non-null   float64
 8   TotalCharges                             7032 non-null   float64
 9   Churn                                    7032 non-null   int64
 10  TotalServices                            7032 non-null   int64
 11  LongTermCustomer                         7032 non-null   int64
 12  MultipleLines_No                         7032 non-null   int64
 13  MultipleLines_No phone service           7032 non-null   int64
 14  MultipleLines_Yes                        7032 non-null   int64
 15  InternetService_DSL                      7032 non-null   int64
 16  InternetService_Fiber optic              7032 non-null   int64
 17  InternetService_No                       7032 non-null   int64
 18  OnlineSecurity_No                        7032 non-null   int64
 19  OnlineSecurity_No internet service       7032 non-null   int64
 20  OnlineSecurity_Yes                       7032 non-null   int64
 21  OnlineBackup_No                          7032 non-null   int64
 22  OnlineBackup_No internet service         7032 non-null   int64
 23  OnlineBackup_Yes                         7032 non-null   int64
 24  DeviceProtection_No                      7032 non-null   int64
 25  DeviceProtection_No internet service     7032 non-null   int64
 26  DeviceProtection_Yes                     7032 non-null   int64
 27  TechSupport_No                           7032 non-null   int64
 28  TechSupport_No internet service          7032 non-null   int64
 29  TechSupport_Yes                          7032 non-null   int64
 30  StreamingTV_No                           7032 non-null   int64
 31  StreamingTV_No internet service          7032 non-null   int64
 32  StreamingTV_Yes                          7032 non-null   int64
 33  StreamingMovies_No                       7032 non-null   int64
 34  StreamingMovies_No internet service      7032 non-null   int64
 35  StreamingMovies_Yes                      7032 non-null   int64
 36  Contract_Month-to-month                  7032 non-null   int64
 37  Contract_One year                        7032 non-null   int64
 38  Contract_Two year                        7032 non-null   int64
 39  PaymentMethod_Bank transfer (automatic)  7032 non-null   int64
 40  PaymentMethod_Credit card (automatic)    7032 non-null   int64
 41  PaymentMethod_Electronic check           7032 non-null   int64
 42  PaymentMethod_Mailed check               7032 non-null   int64
 43  TenureGroup_0-12                         7032 non-null   int64
 44  TenureGroup_13-24                        7032 non-null   int64
 45  TenureGroup_25-48                        7032 non-null   int64
 46  TenureGroup_49-72                        7032 non-null   int64
 47  MonthlyChargeCategory_High               7032 non-null   int64
 48  MonthlyChargeCategory_Low                7032 non-null   int64
 49  MonthlyChargeCategory_Medium             7032 non-null   int64
dtypes: float64(2), int64(48)
memory usage: 2.7 MB

In [45]:
df.shape

(7032, 50)

In [46]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'PaperlessBilling', 'MonthlyCharges', 'TotalCharges',
       'Churn', 'TotalServices', 'LongTermCustomer', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'TenureGroup_0-12', 'TenureGroup_13-24', 'TenureGroup_25-48',
       'TenureGroup_49-72', 'MonthlyChargeCategory_High',
       'MonthlyChargeCategory_Low', 'MonthlyChargeCategory_Medium'],
      dtype='object')

In [47]:
df['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

### Observation

The encoded dataset contains only numerical features needed for machine learning. The target variable ('Churn') is represented as binary values (0,1), making it appropriate for binary classification models.

In [48]:
# Seperate Features and Target Variables

x=df.drop("Churn",axis=1)
y=df['Churn']

In [49]:
print(x.shape)
print(y.shape)
x.head()

(7032, 49)
(7032,)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,TotalServices,...,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,TenureGroup_0-12,TenureGroup_13-24,TenureGroup_25-48,TenureGroup_49-72,MonthlyChargeCategory_High,MonthlyChargeCategory_Low,MonthlyChargeCategory_Medium
0,0,0,1,0,1,0,1,29.85,29.85,2,...,0,1,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,0,56.95,1889.50,5,...,0,0,1,0,0,1,0,0,0,1
2,1,0,0,0,2,1,1,53.85,108.15,4,...,0,0,1,1,0,0,0,0,0,1
3,1,0,0,0,45,0,0,42.30,1840.75,5,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,2,1,1,70.70,151.65,2,...,0,1,0,1,0,0,0,1,0,0

### Observation

The predictor variables were seperated from the target variable. The feature matrix ("X") contains all customer attributes, while the target vector ("Y") contains the churn labels used for model training.

In [50]:
# Train-Test-Split

x_train,x_test,y_train,y_test= train_test_split(
    x,
    y,
    random_state=42
)

In [51]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5274, 49)
(1758, 49)
(5274,)
(1758,)

### Observation

The dataet was divided into training (80%) and testing (20%) subsets. The training data will be used to train the models, while the testing data will be used to evaluate their perfomance on unseen data.

## Feature scaling

Since Logistic Regression is sensitive to feature scales, the numerical features are standardized using "StandardScaler". The scaler is fitted only on th training data and the applied to the testing data to prevent dta leakage.

In [52]:
# import libraries

from sklearn.preprocessing import StandardScaler

In [54]:
scaler=StandardScaler()
x_train_scaled= scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [55]:
print(x_train_scaled.shape)
print(x_test_scaled.shape)

(5274, 49)
(1758, 49)

### Observation

The training data was standardized using "StandardScaler", and the same transformation was applied to the testing data. Scaling ensures that numerical features have a range , improving the performance of the algorithms such as Logistic Regression.